services:
  - type: web
    name: astrobot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /status
