services:
  - type: web
    name: astrobot-backend
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn run:app --bind=0.0.0.0:10000 --workers=4 --worker-class=gevent --timeout=30
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHON_VERSION
        value: "3.9.13"
      - key: PORT
        value: "10000"
    healthCheckPath: /status
    autoDeploy: true
